/*
 * Inits for Broadcom PHY core tables,
 * Networking Adapter Device Driver.
 *
 * THE CONTENTS OF THIS FILE IS TEMPORARY.
 * Eventually it'll be auto-generated.
 *
 * Copyright(c) 2012 Broadcom Corp.
 * All Rights Reserved.
 *
 * $Id$
 */

#include <typedefs.h>
#include <wlc_cfg.h>

#include "wlc_phy_int.h"
#include "wlc_phy_radio.h"
#include "wlc_phytbl_acdc.h"


/* Channel Info table for 2069 rev16/17 (4335 A0).
 * using 40MHz crystal
 * Auto-generated by running tunedb2tcl_2069.sh
 */

/* Tuning file for 40MHz Crystal */
chan_info_radio20691_t chan_tuning_20691rev_1[] = {
	{ 184,    4920 },
	{ 185,    4925 },
	{ 187,    4935 },
	{ 188,    4940 },
	{ 189,    4945 },
	{ 192,    4960 },
	{ 196,    4980 },
	{ 207,    5035 },
	{ 208,    5040 },
	{ 209,    5045 },
	{ 210,    5050 },
	{ 212,    5060 },
	{ 216,    5080 },
	{ 34,    5170 },
	{ 36,    5180 },
	{ 38,    5190 },
	{ 40,    5200 },
	{ 42,    5210 },
	{ 44,    5220 },
	{ 46,    5230 },
	{ 48,    5240 },
	{ 52,    5260 },
	{ 54,    5270 },
	{ 56,    5280 },
	{ 58,    5290 },
	{ 60,    5300 },
	{ 62,    5310 },
	{ 64,    5320 },
	{ 100,    5500 },
	{ 102,    5510 },
	{ 104,    5520 },
	{ 106,    5530 },
	{ 108,    5540 },
	{ 110,    5550 },
	{ 112,    5560 },
	{ 114,    5570 },
	{ 116,    5580 },
	{ 118,    5590 },
	{ 120,    5600 },
	{ 122,    5610 },
	{ 124,    5620 },
	{ 126,    5630 },
	{ 128,    5640 },
	{ 130,    5650 },
	{ 132,    5660 },
	{ 134,    5670 },
	{ 136,    5680 },
	{ 138,    5690 },
	{ 140,    5700 },
	{ 142,    5710 },
	{ 144,    5720 },
	{ 145,    5725 },
	{ 146,    5730 },
	{ 147,    5735 },
	{ 148,    5740 },
	{ 149,    5745 },
	{ 151,    5755 },
	{ 153,    5765 },
	{ 155,    5775 },
	{ 157,    5785 },
	{ 159,    5795 },
	{ 161,    5805 },
	{ 165,    5825 },
	{ 1,    2412 },
	{ 2,    2417 },
	{ 3,    2422 },
	{ 4,    2427 },
	{ 5,    2432 },
	{ 6,    2437 },
	{ 7,    2442 },
	{ 8,    2447 },
	{ 9,    2452 },
	{ 10,    2457 },
	{ 11,    2462 },
	{ 12,    2467 },
	{ 13,    2472 },
	{ 14,    2484 },
};


/* 20691 rev1 register dumping and initialization tables */
#if defined(BCMDBG)
#if defined(DBG_PHY_IOV)

radio_20xx_dumpregs_t dumpregs_20691_rev1[] = {
	{ 0x0000 | JTAG_2069_CR0},
	{ 0x0000 | JTAG_2069_PLL},
	{ 0xFFFF,               }
};

#endif	
#endif	

radio_20xx_prefregs_t prefregs_20691_rev1[] = {
	{ 0x0041 | JTAG_2069_CR0,	0x0},
	{ 0xFFFF,			0x0}
};

uint16 acphy_txgain_epa_2g_20691rev1[] = {
	0x1044, 0x7F03, 0xFFFF,
};

uint16 acphy_txgain_epa_5g_20691rev1[] = {
	0x0044, 0x7F1F, 0xFFFF,
};

uint16 acphy_txgain_ipa_2g_20691rev1[] = {
	0x0044, 0xefff, 0xf7ff,
};

uint16 acphy_txgain_ipa_5g_20691rev1[] = {
	0x00ff, 0xffff, 0xffff,
};
