/* this file is automatically generated from top level Makefile */
#ifndef __BCM_SWVERSION_H__
#define __BCM_SWVERSION_H__
#define BCM_REL_VERSION 4
#define BCM_REL_RELEASE 12
#define BCM_REL_PATCH 6
#define BCM_SW_VERSIONCODE (4*65536+12*256+6)
#define BCM_SW_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))
#endif
